### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dajare** [eybmv/edgar-rice-burroughs_tarzan-lord-of-the-jungle#1]
**Fixes needed**

- [x] cases of unsemanticated `<i>` in cc. 1, 5, 6, 12 -> should be `<em>`
    - for `<i>simm</i>` in c21 -> `<i xml:lang="und">simm</i>`
    - I think the extended quotes in `<i>` in cc. 21 (×2) and 24 (×5) can stand as-is
- [x]  `Allen St. John` in `colophon.xhtml` -> needs `abbr` wrapper for `St.`
- [x]  in `content.opf`, lines 66 and 67 should be inverted (`file-as` precedes `full-name`)
- [x]  Wikipedia link for the book is incorrect -> `https://en.wikipedia.org/wiki/Tarzan,_Lord_of_the_Jungle_(novel)`
- [x]  I think the second paragraph in the Long Description would benefit from a tweak or two: (1) `This book marks a significant transition from previous novels.` -> `...previous novels in the series.` (It otherwise sounds like you're making a claim for literature as a whole!) (2) `Whereas books prior` -> `Whereas earlier books`. (This paragraph seems to owe something to that Wikipedia page, but probably sufficiently distinct for an SE long description.)
- [x] **UPDATE** Vince replied on Google Groups re: the first comment, below. The `cover.source.jpg` is a PNG file, and these [are allowed](https://standardebooks.org/manual/1.8.0/single-page#10.1), so you'll need to rename that file and commit the new one. Good idea also to run `se build-images` when you're done.

**Comments**

- `se build-images` flags: `*Error*  Invalid JPEG file:` pointing to `cover.source.jpg`. It renders fine for me, and I have no idea while build-images regards it as "invalid"; I'll ask about this in Google Groups.
- second `semanticate` commit includes a typography fix, not much point rebasing that out, I don't think.

**Comment by eybmv** [comment]
Thanks! I think I may have just... straight up forgot to check for <i> ...

- Out of curiosity, why would extended quotes be okay in `<i>` as opposed to `<em>`?
- I gave a given name abbr for St. John, is that correct? Also would his name need that tag in the content.opf as well?

**Comment by dajare** [comment]
Hi Elizabeth - 

> * Out of curiosity, why would extended quotes be okay in `<i>` as opposed to `<em>`?

Because `em` is for "**em**phasis" (as I know you know!), and those extended quotes in italics are not being *emphasized*: it's simply a signal of a longer quote. [Here are some examples](https://github.com/search?q=org%3Astandardebooks+%2F%3Ci%3E%5Ba-zA-Z+%2C%5D%7B25%2C%7D%3C%5C%2Fi%3E%2F+path%3Asrc%2Fepub%2Ftext%2Fch*.xhtml&type=code), although there's quite a few false positives in there.

> * I gave a given name abbr for St. John, is that correct? Also would his name need that tag in the content.opf as well?

`content.opf` doesn't get any `abbr` tags, only `colophon.xhtml`; and no, the given name semantic is not correct. "St." is not abbreviating a "given name", it is an abbreviation for "Saint", so just gets simple `<abbr>` - [as you can see here](https://github.com/search?q=org%3Astandardebooks%20%2F%3Cabbr%3ESt.%3C%2F%20path%3Asrc%2Fepub%2Ftext%2Fcolophon.xhtml&type=code) ;-)

So if you could just tweak that `<abbr>St.</abbr>` in `colophon.xhtml`, I'll look over the other commits. Hopefully we're good to go!

**Comment by dajare** [comment]
P.s. I see you've simply changed all `i` to `em` in 3a70b77 ("Add italics" probably not the most accurate commit message! The italics were already there: better would have been "Changed i tags to em"). Let's leave it that way and we'll see what Alex says about the longer ones in cc 21 and 24.

**But!** You have also introduced a rogue `/` in [c.5 line 42][542] - that will need to be fixed, too.

[542]: https://github.com/eybmv/edgar-rice-burroughs_tarzan-lord-of-the-jungle/blob/8852294d2e27658e9280dde7a84c85cc6c2c635b/src/epub/text/chapter-5.xhtml#L42

**Comment by eybmv** [comment]
Ohhh I see. Yeah, true the commit names could have stood to be a bit better :)) I think I got most things fixed!

**Comment by eybmv** [comment]
Could we hazard a guess that simm is Arabic or do we just not want to touch that?

**Comment by dajare** [comment]
> Could we hazard a guess that simm is Arabic or do we just not want to touch that?

I checked for that, in fact, during the initial review and could not turn up any trace. Safest just to stick with what we've got, I think. Better not to guess! It can be updated should we learn differently.
